### ISSUE TITLE
[Pimcore 11 / Bug] Admin UI light theme does not contrast with icons

### ISSUE THREAD

**Issue by NiklasBr** [elements-at/ProcessManager#201]
Related to: https://github.com/coreshop/CoreShop/issues/2566

With the light theme the menu icon looks like:
![image](https://github.com/elements-at/ProcessManager/assets/279826/4f3ca774-8efb-4ff5-84b6-6a8220c3a52f)

And on hover:
![image](https://github.com/elements-at/ProcessManager/assets/279826/2d81583f-14e8-44c1-b124-8e795d69466a)

This is the full CSS path selector to the `li` menu item, unfortunately I cannot find anything which signals the light theme is used:
```css
html#ext-element-6.x-viewport
body#ext-element-1.pimcore_version_11.x-gecko.x-windows.x-desktop.x-body.x-keyboard-mode.x-border-box.x-scroller.x-container.x-container-default
div#pimcore_sidebar.with-notifications
div#pimcore_navigation
ul#pimcore_navigation_ul
li#plugin_pm_shortcut_menu.pimcore_menu_item.true-initialized
```

Pimcore themselves resolved it by inverting the icons in `pimcoreadminuiclassiclighttheme/css/admin.css`:

```css
#pimcore_navigation .x-menu-item-icon, .pimcore_navigation_flyout .x-menu-item-icon-default, .pimcore_panel_toolbar_horizontal .pimcore_main_toolbar .x-btn-icon-el, .pimcore_panel_toolbar_horizontal_border_layout .pimcore_main_toolbar .x-btn-icon-el, .pimcore_editor_tabbar .x-tab-icon-el, .pimcore_main_accordion .pimcore_icon_material, .pimcore_headbar_submenu_menu .x-menu-item-icon, .x-menu .pimcore_nav_icon_custom_report_default, #pimcore_panel_tabs > .x-panel-bodyWrap > .x-tab-bar .x-tab-bar-body .backend_power_tools_admin_bookmark_list {
    filter: invert(0.7);
}
```
